sorenlouv/backport

src/cli/test/__snapshots__/cliService.test.js.snap, src/cli/test/__snapshots__/steps.test.js.snap, src/lib/git.js
Untracked files won't be removed with `git reset --hard`. In some edge cases, there will be untracked files, which must be removed, before a checkout to master can occur.
This PR ensures that untracked files are removed before cherry-picking occurs.
=> Clean branch before cherry-picking

readme.MD, src/cli/index.js, src/cli/steps.js, src/cli/test/__snapshots__/steps.test.js.snap, src/lib/configTemplate.json
Currently it is possible to specify `multiple` in the config. `true` will give the user a checkbox (instead of a single select list), and the user can choose multiple commits to backport, and multiple versions to backport to. 
The issue is, that most of the time the user might just select a single commit but multiple versions to backport to. In those cases, it is much easier to have a "select list" instead of checkboxes when picking the commit, while still having the checkboxes for versions.
=> Distinguish between multiple commits and multiple versions

README.md
=> Mention that `upstream` is used to override project-specific configs

.gitignore, src/cli/cliService.js, src/lib/errors.js, src/lib/git.js, src/lib/github.js, test/__snapshots__/steps.test.js.snap, test/git.test.js
=> Gracefully abort if user does not have proper ssh access to github

package.json
The node version in the engines section of the package.json file was out of sync with the nvmrc file. As a result, installing this in node 6 wasn't an issue, but the postinstall script fails.
This will make npm/yarn show a warning when installing in node 6.
=> fix: make engines match nvmrc

package.json, scripts/postinstall.js
Windows doesn't like shebangs in the beginning of JS files. Instead just directly execute via `node` using the `package.json`.
=> Fix broken shebang on windows

src/lib/git.js, test/__snapshots__/cliService.test.js.snap, test/__snapshots__/steps.test.js.snap
Before this change, my local git (version 2.14.1) was setting `6.x` as the remote branch for a local `backport/6.x/pr-20572`. This will ensure the right name is used.
Thanks @sqren for helping me to debug this issue!
=> Explicitly set remote branch name when doing git push

CONTRIBUTING.md, package.json, src/options/options.ts, src/services/env.ts, src/services/git.ts, src/services/github.ts, src/steps/doBackportVersions.ts, src/steps/getCommits.ts, src/steps/maybeSetupRepo.ts, src/steps/steps.ts, test/.eslintrc.json, test/services/env.test.ts, test/services/git.test.ts, test/services/github.test.ts, test/steps/doBackportVersions.test.ts, test/steps/getCommits.test.ts, test/steps/maybeSetupRepo.test.ts, test/steps/steps.test.ts, yarn.lock
A bit of cleanup - no user-facing changes
- Remove `setAccessToken` setter
- Preserve `options` object
- Simplify tests
=> Preserve `BackportOptions` object and simplify tests

README.md, src/options/cliArgs.ts, src/services/github/fetchCommitsByAuthor.ts, src/steps/getCommits.ts, src/types/Config.ts, test/integration/__snapshots__/integration.test.ts.snap, test/unit/options/options.test.ts, test/unit/services/github/__snapshots__/fetchCommitsByAuthor.test.ts.snap, test/unit/steps/__snapshots__/steps.test.ts.snap, test/unit/steps/steps.test.ts
This makes it possible to only list commits that touches files under a specified path.
Example usage:
```
backport --all --path x-pack/legacy/plugins/apm
```
=> Add `path` option

README.md, src/options/cliArgs.test.ts, src/options/cliArgs.ts, src/options/options.test.ts, src/services/git.ts, src/steps/doBackportVersions.ts, src/steps/steps.test.ts
Closes #146
Add `--reset-author` flag which makes it possible to change the commit author to yourself.
This is useful when the original commit was made by a bot and the the CLA check needs to be bypassed.
Example usage:
```
backport --reset-author
```
@spalger
=> Add `--reset-author` flag

src/options/__snapshots__/options.test.ts.snap, src/options/options.ts
Previously the CLI would display the error message with `acccessToken`, which doesn't match the actual param name.
=> Fix “accessToken” options typo

src/options/options.test.ts, src/services/github/__snapshots__/fetchCommitBySha.test.ts.snap, src/services/github/addLabelsToPullRequest.ts, src/services/github/createPullRequest.ts, src/services/github/fetchCommitBySha.ts, src/services/github/verifyAccessToken.test.ts, src/services/github/verifyAccessToken.ts, src/ui/cherrypickAndCreatePullRequest.test.ts, src/ui/getCommitBySha.test.ts
Github is deprecating sending access token via query param. Instead it should be sent over auth header
https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters
Closes #164
=> Send access token via auth header

README.md, docs/configuration.md, src/options/cliArgs.test.ts, src/options/cliArgs.ts, src/options/config/config.test.ts, src/options/config/config.ts, src/options/options.test.ts, src/runWithOptions.test.ts, src/services/github/__snapshots__/fetchCommitsByAuthor.test.ts.snap, src/services/github/addLabelsToPullRequest.ts, src/services/github/createPullRequest.ts, src/services/github/fetchAuthorId.ts, src/services/github/fetchCommitByPullNumber.ts, src/services/github/fetchCommitBySha.test.ts, src/services/github/fetchCommitBySha.ts, src/services/github/fetchCommitsByAuthor.test.ts, src/services/github/fetchCommitsByAuthor.ts, src/services/github/getDefaultRepoBranch.ts, src/services/github/gqlRequest.test.ts, src/services/github/gqlRequest.ts, src/services/github/mocks/getExistingBackportPRsMock.ts, src/services/github/verifyAccessToken.test.ts, src/services/github/verifyAccessToken.ts, src/services/logger.ts, src/test/getDefaultOptions.ts, src/types/Config.ts, src/ui/cherrypickAndCreatePullRequest.test.ts, src/ui/getCommitBySha.test.ts, yarn.lock
Closes #163
Summary:
- Add options `githubApiBaseUrlV3` and `githubApiBaseUrlV4` and remove `apiHostname`
- Fix version alias ('-v') (#163)
- Refresh yarn.lock file
This PR removes the option `apiHostname` which primarily consumed by Github Enterprise users. They will instead have to specify two options: `githubApiBaseUrlV3` and `githubApiBaseUrlV4`.
This is a breaking change and will be released as a major version bump
=> Add options `githubApiBaseUrlV3` and `githubApiBaseUrlV4` and remove `apiHostname`

src/__snapshots__/runWithOptions.test.ts.snap, src/runWithArgs.ts, src/services/github/Commit.d.ts, src/services/github/__snapshots__/fetchCommitsByAuthor.test.ts.snap, src/services/github/commitFormatters.ts, src/services/github/fetchCommitByPullNumber.ts, src/services/github/fetchCommitBySha.test.ts, src/services/github/fetchCommitBySha.ts, src/services/github/fetchCommitsByAuthor.test.ts, src/services/github/fetchCommitsByAuthor.ts, src/services/github/mocks/commitsByAuthorMock.ts, src/services/github/mocks/getExistingBackportPRsMock.ts, src/services/github/mocks/getPullRequestEdgeMock.ts, src/services/prompts.ts, src/test/integration/__snapshots__/integration.test.ts.snap, src/ui/cherrypickAndCreatePullRequest.test.ts, src/ui/cherrypickAndCreatePullRequest.ts, src/ui/getCommitBySha.test.ts
This improves the heuristic for finding related pull requests by also matching against the title of the potentially related pull request.
=> Improve heuristic for finding related pull requests

src/runWithArgs.ts, src/runWithOptions.ts, src/services/git.ts, src/services/github/__snapshots__/fetchCommitsByAuthor.test.ts.snap, src/services/github/fetchCommitsByAuthor.test.ts, src/services/github/fetchCommitsByAuthor.ts, src/services/github/mocks/commitsByAuthorMock.ts, src/services/github/mocks/getCommitsByAuthorMock.ts, src/services/github/mocks/getPullRequestEdgeMock.ts, src/services/logger.ts, src/test/integration/__snapshots__/integration.test.ts.snap, src/ui/cherrypickAndCreatePullRequest.test.ts, src/ui/cherrypickAndCreatePullRequest.ts
- Find related backports by looking at `mergedCommit.oid`
- Improve error reporting by writing the error.message in console and the rest in logs
- Change `setInterval` to recursive `setTimeout` to avoid flooding with requests (mostly relevant for huge git repos)
Follow-up https://github.com/sqren/backport/pull/170
=> Find related backports by looking at `mergedCommit.oid`

src/services/git.test.ts, src/services/git.ts, src/services/logger.ts, src/ui/__snapshots__/cherrypickAndCreatePullRequest.test.ts.snap, src/ui/cherrypickAndCreatePullRequest.test.ts, src/ui/cherrypickAndCreatePullRequest.ts
=> Split conflict resolution and staging into separate steps

README.md, docs/configuration.md, package.json, src/options/cliArgs.ts, src/options/options.test.ts, src/runWithOptions.test.ts, src/services/child-process-promisified.ts, src/services/git.test.ts, src/services/git.ts, src/test/ExecError.ts, src/test/integration/__snapshots__/integration.test.ts.snap, src/ui/__snapshots__/cherrypickAndCreatePullRequest.test.ts.snap, src/ui/cherrypickAndCreatePullRequest.test.ts, src/ui/cherrypickAndCreatePullRequest.ts
Closes https://github.com/sqren/backport/issues/150
Released as 5.1.6-beta.1: 
```
npm install backport@5.1.6-beta.1
```
=> Add `mainline` option

src/ui/cherrypickAndCreatePullRequest.test.ts, src/ui/cherrypickAndCreateTargetPullRequest.ts
Closes #193 
Prints the repo path before the files which are conflicting to make it easier to open the entire repo when desired.
=> print the repo path on conflicts

README.md, docs/configuration.md, src/options/cliArgs.test.ts, src/options/cliArgs.ts, src/options/options.test.ts, src/runWithOptions.test.ts, src/services/github/v3/addAssigneesToPullRequest.test.ts, src/services/github/v3/addAssigneesToPullRequest.ts, src/services/github/v3/createPullRequest.ts, src/test/integration/__snapshots__/integration.test.ts.snap, src/ui/cherrypickAndCreatePullRequest.test.ts, src/ui/cherrypickAndCreateTargetPullRequest.ts
Closes https://github.com/sqren/backport/issues/188
**Example: assign yourself to the backport pull request**
```
backport --auto-assign
```
if you always want to assign yourself to your backport PRs you can add the following to `.backport/config.json`:
```json
{
"autoAssign": true
}
```
**Example: assign another user to the backport pull request:**
```
backport --assign watson
```
=> Add options: `auto-assign` and `assignees`

src/options/ConfigOptions.ts, src/options/options.test.ts, src/services/git.test.ts, src/services/git.ts, src/services/github/v4/fetchCommitsByAuthor.ts, src/ui/cherrypickAndCreateTargetPullRequest.ts, src/ui/getTargetBranches.test.ts, src/ui/getTargetBranches.ts
- improve `backport --pr 123` when source branch is non-master
- `autoFixConflicts` should support async return types
=> Respect source branch from commit

src/options/ConfigOptions.ts, src/ui/cherrypickAndCreateTargetPullRequest.ts
The autoFix strategy we're looking to implement depends on the branch which the backport is being created for, so it's important that we can access the targetBranch for the backport in our autofix handler.
(CODEOWNERS file should only be on master, if backport is to a non-master branch we should delete CODEOWNERS when it's conflicting)
=> [autoFixConflicts] pass `targetBranch` to handler

package.json, src/__snapshots__/runWithOptions.test.ts.snap, src/services/git.test.ts, src/services/git.ts, src/services/prompts.ts, src/test/integration/__snapshots__/integration.test.ts.snap, src/ui/__snapshots__/cherrypickAndCreatePullRequest.test.ts.snap, src/ui/cherrypickAndCreatePullRequest.test.ts, src/ui/cherrypickAndCreateTargetPullRequest.ts, yarn.lock
Closes https://github.com/sqren/backport/issues/219
=> Do not automatically stage files

src/options/ConfigOptions.ts, src/services/github/v3/createPullRequest.ts, src/services/github/v4/FetchPullRequestId.ts, src/services/github/v4/disablePullRequestAutoMerge.ts, src/services/github/v4/enablePullRequestAutoMerge.private.test.ts, src/services/github/v4/enablePullRequestAutoMerge.ts, src/services/github/v4/fetchPullRequestAutoMergeMethod.ts, src/ui/cherrypickAndCreateTargetPullRequest.ts
=> Fix issue with enabling auto merging for PRs

README.md, src/options/ConfigOptions.ts, src/options/cliArgs.ts, src/options/config/config.test.ts, src/options/config/config.ts, src/options/options.test.ts, src/runWithOptions.test.ts, src/services/git.integration.test.ts, src/services/git.ts
Closes https://github.com/sqren/backport/issues/243
- `cherrypickRef` option will append "(cherry picked from commit...)" to commit message. 
- `cherrypickRef` will default to to and can be disabled with `--no-cherrypick-ref`
=> By default append "(cherry picked from commit...)" to commit message. Disable with `--no-cherrypick-ref`

src/options/cliArgs.test.ts, src/options/cliArgs.ts, src/options/options.test.ts, src/options/options.ts, src/test/inquirer.private.test.ts, src/utils/excludeUndefined.test.ts, src/utils/excludeUndefined.ts
Regression from #283 
- The `--all` flag was mistakenly ignored. This fixes the bug and adds missing test coverage
- This also removes `mainline` argument by default (I don't know how it ended up being applied by default).
=> `--all` should be respected

.gitignore, .vscode/launch.json, README.md, docs/configuration.md, src/entrypoint.module.ts, src/main.ts, src/options/ConfigOptions.ts, src/options/cliArgs.ts, src/options/config/config.test.ts, src/options/config/config.ts, src/options/config/globalConfig.test.ts, src/options/config/globalConfig.ts, src/options/options.test.ts, src/options/options.ts, src/runSequentially.test.ts, src/services/env.test.ts, src/services/env.ts, src/services/git.ts, src/services/github/v3/createStatusComment.test.ts, src/services/github/v3/createStatusComment.ts, src/services/github/v4/fetchRemoteProjectConfig.private.test.ts, src/services/github/v4/fetchRemoteProjectConfig.ts, src/services/github/v4/getOptionsFromGithub/getOptionsFromGithub.ts, src/services/logger.ts, src/test/backport-e2e.private.test.ts, src/test/handleUnbackportedPullRequests.private.test.ts, src/ui/cherrypickAndCreateTargetPullRequest.ts, src/ui/maybeSetupRepo.test.ts, src/ui/maybeSetupRepo.ts, src/utils/redact.ts
Closes https://github.com/sqren/backport/issues/269
This adds a new `--dir` option where the temporary repo will be checked out, and where conflicts should be resolved.
The global config file will still be retrieved from `~/.backport/config.json`
Summary:
- Add options `dir` and `publishStatusComment`
- redact access-token when posting status comment
=> Add `--dir` flag

.travis.yml, jest.config.js, jest.config.mutation.js, package.json, src/options/cliArgs.test.ts, src/options/cliArgs.ts, src/test/backport-e2e.mutation.test.ts, src/test/inquirer.private.test.ts
Some tests mutate shared state (eg changes the state of Github pull requests) and can thus not be run in parallel. They still have value but should only be run locally.
=> Disable tests with mutations on CI

src/backportRun.ts, src/entrypoint.module.private.test.ts, src/lib/github/v4/validateTargetBranches.private.test.ts, src/lib/github/v4/validateTargetBranches.ts, src/options/options.ts
The previous check only validation target branches provided at runtime. This will also validate target branches provided via labels (`branchLabelMapping`)
=> Improve validation of target branches

src/lib/github/v3/createStatusComment.test.ts, src/lib/github/v3/createStatusComment.ts, src/lib/github/v4/getOptionsFromGithub/getOptionsFromGithub.private.test.ts, src/lib/github/v4/getOptionsFromGithub/getOptionsFromGithub.ts, src/lib/github/v4/getOptionsFromGithub/query.ts, src/options/options.test.ts
Closes https://github.com/sqren/backport/issues/320
Shield.io badges cannot be displayed for private repos and currently show an error like:
| Status | Branch | Result |
|:------:|:------:|:------|
|✅|7.x|[<img src="https://img.shields.io/github/pulls/detail/state/sqren/backport-private/297">](https://github.com/sqren/backport/pull/297)|
This PR changes this, so badges are only displayed for public repos. For private repos the link to the PR will simply be displayed.
| Status | Branch | Result |
|:------:|:------:|:------|
|✅|7.x|[<img src="https://img.shields.io/github/pulls/detail/state/sqren/backport/297">](https://github.com/sqren/backport/pull/297)|
| Status | Branch | Result |
|:------:|:------:|:------|
|✅|7.x|https://github.com/sqren/backport/pull/297|
=> fix: only show shield.io badge for public repos

src/lib/git.test.ts, src/lib/git.ts, src/options/ConfigOptions.ts, src/options/cliArgs.ts, src/options/options.test.ts, src/options/options.ts, src/test/e2e/cli/entrypoint.cli.private.test.ts
Apologies for jumping the gun here but since this is a fairly simple addition, I went ahead and created a PR. Hope this makes it in :)
Fixes https://github.com/sqren/backport/issues/335
=> Add signoff option

src/lib/child-process-promisified.ts, src/lib/git.ts, src/lib/setupRepo.test.ts
Backport currently expects an English locale, since it parses error messages from git. To ensure English local all git messages not set the `LANG` environment variable to `en_US.UTF-8`. This means that the following will not cause errors:
```
LANG=it.UTF-8 backport 
```
=> Ensure english locale

src/lib/setupRepo.ts
When running backport from inside the backport dir an error is thrown:
> Refusing to clone repo into "/Users/sqren/.backport/repositories/elastic/kibana" when current working directory is "/Users/sqren/.backport/repositories/elastic/kibana". Please change backport directory via `--dir` option or run backport from another location
This is overly restrictive. It should be possible to run backport from within the backport dir itself if it exists.
=> Allow running backport from backport dir

src/lib/__snapshots__/cherrypickAndCreateTargetPullRequest.test.ts.snap, src/lib/author.ts, src/lib/cherrypickAndCreateTargetPullRequest.ts, src/lib/git.private.test.ts, src/lib/git.ts, src/lib/setupRepo.test.ts, src/options/options.ts, src/test/e2e/cli/commit-author.private.test.ts
Currently the backport commit author defaults to using the info from the git config. This PR changes that so the backport commit author will instead inherit the author from the source commit.
To override this behaviour the user can set the commit author explicitly like `backport --git-author-name="Donald Duck" --git-author-email="duck@disney.com"`
=> Prefer commit author from source commit

src/lib/git.ts
Fixing [issue 440](https://github.com/sqren/backport/issues/440):
Problem:
On Windows 10 Backport will always clone, because the projectRoot & repoPath never will be equal, even though they do exist.
A problem with \ vs / . 
My solution is to add path.normalize() which should work on both Windows and POSIX.
Feel free to adapt my solution as needed.
Test executed:
Run 1st time: Repo cloned
Run 2nd time: Repo pulled
Run 3th time (after deleting the repo): Repo cloned
=> Fix cloning vs pulling by normalizing path

package.json, src/lib/apm.ts, yarn.lock
v3.47.0 refactored is internal transport code to new names, 
which broke how backport was reaching in and using it.
=> Fix usage of elastic-apm-node@3.47.0 and later

.vscode/launch.json, jest.config.ts, src/lib/cherrypickAndCreateTargetPullRequest/cherrypickAndCreateTargetPullRequest.ts, src/lib/cherrypickAndCreateTargetPullRequest/waitForCherrypick.ts, src/lib/git.ts, src/lib/sequentially.ts, src/options/ConfigOptions.ts, src/options/cliArgs.ts, src/options/options.test.ts, src/options/options.ts, src/test/e2e/cli/entrypoint.cli.private.test.ts
Previously if the backport tool encountered conflicts it would allow the user to resolve them manually, or when running in non-interactive mode in CI it would abort.
This PR introduces `commitConflicts: boolean` option. It is disabled by default. When enabled it will commit conflicting files when running on CI.
=> Add support for committing conflicts

src/options/cliArgs.ts, src/test/e2e/cli/entrypoint.cli.private.test.ts
[yargs](https://github.com/yargs/yargs/blob/main/docs/api.md#exitprocessenable) will call `process.exit` after outputting the help section. When running backport as a child process and reading the output async, the exit command will be called before the full output is written. This can be prevented by calling `.exitProcess(false)`
=> Fix test where CLI output is cutoff at 8192 bytes

package.json
Hey @sqren, I see there is a security notification for axios version being used in this repo.
```
An issue discovered in Axios 0.8.1 through 1.5.1 inadvertently reveals the confidential XSRF-TOKEN stored in cookies by including it in the HTTP header X-XSRF-TOKEN for every request made to any host allowing attackers to view sensitive information.
```
Bumping version to lowest patched version.
=> bump axios version

docs/config-file-options.md
The text explaining the functionality for `copySourcePRReviewers` appears to be describing what should be controlled by `copySourcePRLabels` (at least that's my assumption based on the field names), and vice-versa.
=> Fix switched descriptions

src/lib/github/v3/createPullRequest.test.ts, src/lib/github/v3/createPullRequest.ts
Fixes an issue where backticks would be escaped when used in the commit message
=> Avoid double-encoding backticks in title template

src/lib/cherrypickAndCreateTargetPullRequest/cherrypickAndCreateTargetPullRequest.ts, src/lib/github/v3/createPullRequest.ts, src/lib/github/v4/enablePullRequestAutoMerge.mutation.test.ts, src/lib/github/v4/fetchExistingPullRequest.private.test.ts, src/options/ConfigOptions.ts, src/options/cliArgs.ts, src/options/options.test.ts, src/options/options.ts, src/test/e2e/cli/entrypoint.cli.private.test.ts
Closes #488 
As it turns out, it seemed pretty easy to implement this myself once I looked through the code a bit. Let me know if you need any changes in order to merge this!
=> Add draft option to publish PRs as drafts

src/lib/child-process-promisified.ts
`LANG=en_US` is not guaranteed to exist on any system (it does not, for
strange reasons, exist on mine). Choose `LANG=C`, which is guaranteed to
exist. It has the side-effect of typically using an encoding other than
UTF-8 for the tool output (e.g., ISO 8859-1). Apart from messages
printed into the log in this encoding that should hopefully have no
negative side-effects.
See https://github.com/sorenlouv/backport/pull/505 for a case where
code was assuming that output would always be English, and failed if it
wasn't.
=> Spawn processes with LANG that's guaranteed to exist

docs/config-file-options.md
While setting up the GitHub Action provided by this project I came across some minor papercuts in the documentation that confused me initially.
See the individual commit messages for details.
- **Documentation: Fix typos**
- **Docs: Use main branch links to source code**
- **Docs: Improve consistency in prTitle documentation**
=> Small documentation improvements

src/lib/git.test.ts, src/lib/git.ts
`deleteRemote()` intends to return successfully if
the to-be-deleted remote does not exist. In this case, git returns an
exit code of 2, and outputs a message to stderr. Depending on the locale
of the user's system, this error message might be localized.
`spawnPromise()` and `spawnStream()` try to set the locale to `en_US`,
but there are no guarantees that this locale is actually available on
the user's system.
Instead of doing fragile locale-dependent string parsing, simply use the
exit code we get from git in this case and act on that.
Fix the mocks in the tests to behave like the real-world git, and add a
test for the non-English case as well.
Fixes #507
=> Properly swallow errors if deleting a remote fails

src/lib/git.test.ts, src/lib/git.ts
Git 2.30.0 introduced a dedicated exit code (2) for when `git remote rm`
failed because the remote does not exist. Earlier versions of git
always returned code 128, and only parsing stderr could tell the error
conditions apart.
Support all versions of git by checking for both exit code 2, and exit
code 128 with the specific error message. The exit code 2 check remains
more robust against localized output, hence it's kept in addition to the
output parsing path that was removed in #505.
Fixes #509
=> Swallow "remote not found" error on git before 2.30

docs/config-file-options.md
Include a direct link to the "new token generation" page on GitHub to
simplify the process for users.
=> Include link to easily generate GH PAT

src/lib/github/v3/createStatusComment.test.ts, src/lib/github/v3/createStatusComment.ts
When a commit message contains a `|` character, this breaks the "All backports failed" comment in GitHub, due to the `|` character  is part of the table markdown. With this PR `|` is escaped with `\|` to ensure the commit message and link are displayed correctly
resolves #512
=> Escape pipe char of commit msg in markdown table 

src/lib/github/v4/enablePullRequestAutoMerge.mutation.test.ts, src/lib/github/v4/fetchCommits/fetchCommitBySha.private.test.ts, src/lib/github/v4/fetchCommits/fetchCommitBySha.ts, src/lib/github/v4/getOptionsFromGithub/getOptionsFromGithub.ts, src/options/config/config.ts, src/options/config/projectConfig.test.ts, src/options/config/projectConfig.ts, src/options/options.ts, src/test/e2e/cli/date-filters.private.test.ts, src/test/e2e/cli/different-merge-strategies.private.test.ts, src/test/e2e/cli/entrypoint.cli.private.test.ts, src/test/e2e/cli/error-handling-interactive-mode.private.test.ts, src/test/e2e/cli/gracefully-handles-corrupt-repo.private.test.ts, src/test/e2e/cli/repo-with-backportrc-removed.private.test.ts, src/test/e2e/cli/repo-with-changing-branchLabelMapping.private.test.ts, src/test/e2e/cli/test-that-repo-can-be-cloned.private.test.ts
Fixes https://github.com/sorenlouv/backport/issues/516
=> Respect config file source branch setting and display in UI

package.json
rn, the license info is wrong on the npmjs side, updating license from MIT to Apache-2.0
=> fix(license): update npmjs license info

src/lib/github/v3/getPullRequest/getPullRequestBody.test.ts, src/lib/github/v3/getPullRequest/getPullRequestBody.ts
Follow up to #526 
This strips markdown comments like ``  in the stringified commit message `{{commitsStringified}}`
=> Strip markdown comments from stringified commits
