package.json, src/cliService.js, test/__snapshots__/cli.test.js.snap, test/cli.test.js
=> Prefix backport PRs with [<branch>] rather than [backport]

package.json, src/configTemplate.json, src/index.js, test/__snapshots__/cli.test.js.snap, yarn.lock
- `multiple`  will default to `true`
- `multiple` and `own` can be specified from .backport config file. This will override the default values (but not options passed through cli)
@epixa
=> Make "multiple" default to true, and add cli options to config

package.json, readme.MD, src/cli/cliService.js, src/cli/index.js, src/cli/steps.js, src/cli/test/steps.test.js, src/lib/github.js, yarn.lock
Add support for supplying a commit sha though the cli, like
```
backport --sha 493ed
```
=> Add CLI option for parsing in a commit sha

README.md
=> Rename to README.md and add suggestions for improvement

package.json, scripts/postinstall.js, src/lib/configs.js
=> Add postinstall script to create global config after install

README.md
@watson had some good suggestions for improving the docs. I added descriptions for all options in the configs, and simplified the example snippets.
=> Improve documentation of configuration options

README.md, package.json, src/cli/cliService.js, src/lib/git.js, src/lib/rpc.js, test/__snapshots__/steps.test.js.snap, test/steps.test.js, yarn.lock
Cloning a repo can take a significant amount of time, and it's currently no possible to the progress. This can make the user worried than an error occurred, and they'll terminate the program.
This PR adds a simple progress indicator to the clone process
=> Add progress indicator to git clone

src/lib/github.ts, src/types/types.ts, test/cliService.test.ts, yarn.lock
=> Ensure sha exists in default branch

src/options/cliArgs.ts, src/options/config/globalConfig.ts, src/options/options.ts, src/steps/doBackportVersions.ts, src/steps/steps.ts, test/options/options.test.ts, test/steps/__snapshots__/steps.test.ts.snap, test/steps/doBackportVersions.test.ts, test/steps/steps.test.ts
=> Add `prDescription` option for specifying extra content in the PR description

README.md, docs/configuration.md, src/options/config/config.ts, src/options/config/globalConfig.ts, src/options/config/projectConfig.ts, src/options/config/readConfigFile.ts, src/options/options.ts, src/services/prompts.ts, src/steps/getBranches.ts, src/steps/getCommits.ts, src/types/Config.ts, test/options/__snapshots__/options.test.ts.snap, test/options/config/projectConfig.test.ts, test/options/options.test.ts
=> Merge config properties to single interface

src/services/github/fetchCommitsByAuthor.ts, test/unit/services/github/fetchCommitsByAuthor.test.ts
Bug reported by @alvarezmelissa87
=> Fix bug related to null pointer in Github API response

README.md, docs/configuration.md, src/options/cliArgs.ts, src/steps/doBackportVersions.ts, src/types/Config.ts, test/unit/options/options.test.ts, test/unit/steps/steps.test.ts
Closes https://github.com/sqren/backport/issues/102
=> Add `editor` option

src/services/github/GithubApiTypes.d.ts, src/services/github/gqlRequest.ts, src/services/github/handleGithubError.ts
=> Fix circular reference with JSON.stringify

src/runWithOptions.ts
Follow-up to https://github.com/sqren/backport/pull/153
=> Add missing await

src/test/yargs.test.ts
This is necessary for contributors who want to run the test suite
=> Fix tests by using ts-node and hardcoding “sqren” as author

README.md, docs/configuration.md
Related to https://github.com/sqren/backport/issues/198
=> Fix docs for `--source-pr-labels`

README.md
The documentation seem to be missing few CLI options when I compared it with the code found in `/src/options/cliArgs.ts` so I decided to update the documentation and add new CLI options that were missing. Also I added a new column called shorthand notation, this was missing. Also I have added proper types such that we do differentiate between array of string and regular strings.
- Some description were outdated and is now corrected to reflect the
code
- The types updated to differentiate between Strings and arrays
- Another column added for shorthand notations
- more CLI options added
- Note about the redudant dashes added
=> Updated the documentation regarding CLI options.

src/entrypoint.cli.e2e.private.test.ts
Missed in https://github.com/sqren/backport/pull/297
=> Fix snapshot

src/backportRun.ts, src/ui/getCommits.ts
=> Suppress console.log when using `—ls`

README.md, docs/configuration.md
Follow up to https://github.com/sqren/backport/pull/336 where I forgot to document this new option :)
=> docs: `signoff` option

src/entrypoint.module.ts, src/lib/getCommits.ts, src/options/ConfigOptions.ts
The following is now supported
```
backport --pr 123 --pr 456
```
=> Add support for backporting multiple PRs at once

src/lib/cherrypickAndCreateTargetPullRequest/cherrypickAndCreateTargetPullRequest.test.ts, src/lib/cherrypickAndCreateTargetPullRequest/cherrypickAndCreateTargetPullRequest.ts
Hey 👋 
Thank you for the great tool - highly appreciated!
I just bumped our Github Actions version, and quickly figured out that auto merging isn't working for us anymore. I tried figuring out what was going on, and we don't have any `Auto merge:`. I found this, and it seems like the logic is incorrect here.
Disclaimer: I haven't tested this, but it looks fairly trivial.
=> fix: auto merge not running when there's no conflicts

docs/cli-options.md, docs/config-file-options.md, src/lib/cherrypickAndCreateTargetPullRequest/cherrypickAndCreateTargetPullRequest.ts, src/lib/cherrypickAndCreateTargetPullRequest/getBackportBranchName.test.ts, src/lib/cherrypickAndCreateTargetPullRequest/getBackportBranchName.ts, src/options/ConfigOptions.ts, src/options/cliArgs.ts, src/options/options.ts, src/test/e2e/cli/entrypoint.cli.private.test.ts
Replaces https://github.com/sqren/backport/pull/476
=> Make the backport branch name used configurable

src/lib/prompts.ts, src/lib/sourceCommit/getPullRequestStates.ts, src/lib/sourceCommit/parseSourceCommit.ts
Fixes https://github.com/sorenlouv/backport/issues/497
=> Fix null pointer when merge conflict is missing

src/lib/cherrypickAndCreateTargetPullRequest/waitForCherrypick.ts, src/lib/child-process-promisified.ts
=> Fix hanging terminal editor during conflict resolution

src/lib/github/v3/createStatusComment.ts, src/options/ConfigOptions.ts, src/options/cliArgs.ts, src/options/options.test.ts, src/options/options.ts, src/test/e2e/cli/date-filters.private.test.ts, src/test/e2e/cli/different-merge-strategies.private.test.ts, src/test/e2e/cli/entrypoint.cli.private.test.ts, src/test/e2e/cli/error-handling-interactive-mode.private.test.ts, src/test/e2e/cli/gracefully-handles-corrupt-repo.private.test.ts, src/test/e2e/cli/repo-with-backportrc-removed.private.test.ts, src/test/e2e/cli/repo-with-changing-branchLabelMapping.private.test.ts, src/test/e2e/cli/test-that-repo-can-be-cloned.private.test.ts
Closes https://github.com/sorenlouv/backport/issues/513
=> Add `—noUnmergedBackportsHelp` option

package.json, src/lib/apm.ts, yarn.lock
Upgrade `elastic-apm-node` from 3.47.0 to 4.10.0
I haven't committed to this repo before; I wasn't 100% sure how to test this, is anyone able to help me out?
=> Upgrading APM library
